# Generated by Django 5.1.2 on 2026-03-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_color_talla_remove_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talla',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='talla',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
