# Generated by Django 5.1.2 on 2026-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_talla_options_talla_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Bodys', 'Bodys'), ('Corset', 'Corset'), ('Top', 'Top'), ('Shorts', 'Shorts'), ('Faldas', 'Faldas'), ('Denim', 'Denim')], max_length=50, null=True),
        ),
    ]
