server {
    # Usaremos el puerto 80 para tráfico normal. Nginx usará el server_name para enrutar el tráfico al proyecto correcto.
    listen 80;
    
    # Nombre del dominio principal y con www.
    server_name byheilynaguilar.com www.byheilynaguilar.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /var/www/tienda_heilyn/staticfiles/;
    }

    location /media/ {
        alias /var/www/tienda_heilyn/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn-tienda.sock;
    }
}
